<?php

namespace App;
use DateTime;
use DateInterval;
use Log;
use Auth;

class C2C {

    const JOB_LEVEL = array(
        1 => 'Executive',
        2 => 'Senior Management',
        3 => 'Mid-Management',
        4 => 'Junior',
        5 => 'Entry Level',
        6 => 'Other'
    );

   const EDUCATION = array(
        1 => 'Less than high school',
        2 => 'High school diploma or equivalent',
        3 => 'Some college',
        4 => 'Associate’s degree',
        5 => 'Bachelor’s degree',
        6 => 'Master’s degree',
        7 => 'Doctoral or professional degree',
   );

   const GENDER = array(
        1 => 'Woman',
        2 => 'Man',
        3 => 'Non-binary',
        4 => 'Trans man',
        5 => 'Trans woman',
        6 => 'Prefer not to disclose',
        7 => 'Identity not listed'
   );

   const EMP_STATUS = array(
        'Unemployed',
        'Student',
        'Self-employed',
        'Part-time employment',
        'Full-time employment',
        'Contractor',
        'Military',
        'Parent',
        'Retired',
        'Other'
   );

   const JOBS = array(
        1   => 'Accountant',
        2   => 'Business & Strategy',
        3   => 'Computer Programmer',
        4   => 'Creative & Design',
        5   => 'Customer Service',
        6   => 'Editorial',
        7   => 'Education',
        8   => 'Engineering',
        9   =>    'Finance and Data',
        10    => 'Fundraising and Development',
        11    => 'HR & Recruiting',
        12    => 'Legal',
        13    => 'Marketing and PR',
        14    => 'Operations',
        15    => 'Product & Project Management',
        16    => 'Real Estate and Construction',
        17    => 'Research and Medicine',
        18    => 'Social Media & Community',
        19    => 'Sales',
        20    => 'Other',
   );

   const REASON = array(
        1 => 'New ways to develop a skill, to learn, and to gain insight into something',
        2 => 'New ways to do what I believe in',
        3 => 'Opportunities to pursue excellence',
        4 => 'Challenging environments',
        5 => 'Enjoyment',
        6 => 'Happiness',
        7 => 'Chances to take it easy',
        8 => 'New ways to test out my skills',
        9 => 'Fun',
        10 => 'Opportunities to contribute to others',
        11 => 'Earning high status and prestige',
        12 => 'Comfort',
        13 => 'Relief',
        14 => 'Personal growth',
        15 => 'Find purpose and meaning',
        16 => 'Other'
   );

   const REFERRAL = array(
		1	=> 'Facebook',
		2	=> 'Instagram',
		3	=> 'Finding Mastery Tribe (Facebook group) ',
		4	=> 'LinkedIn ',
		5	=> 'Pete Carroll’s social media',
		6	=> 'Work referral',
		7	=> 'Referral from friend',
		8	=> 'Find Your Best audiobook',
		9	=> 'Finding Mastery podcast',
		10	=> 'In-person live CTC event',
		11	=> 'Radio/TV ',
		12	=> 'Other ',
   );

   const COUNTRY_CODES = array(
        'US'=>array('name'=>'UNITED STATES','code'=>'1'),
        'AD'=>array('name'=>'ANDORRA','code'=>'376'),
        'AE'=>array('name'=>'UNITED ARAB EMIRATES','code'=>'971'),
        'AF'=>array('name'=>'AFGHANISTAN','code'=>'93'),
        'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
        'AI'=>array('name'=>'ANGUILLA','code'=>'1264'),
        'AL'=>array('name'=>'ALBANIA','code'=>'355'),
        'AM'=>array('name'=>'ARMENIA','code'=>'374'),
        'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'599'),
        'AO'=>array('name'=>'ANGOLA','code'=>'244'),
        'AQ'=>array('name'=>'ANTARCTICA','code'=>'672'),
        'AR'=>array('name'=>'ARGENTINA','code'=>'54'),
        'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'1684'),
        'AT'=>array('name'=>'AUSTRIA','code'=>'43'),
        'AU'=>array('name'=>'AUSTRALIA','code'=>'61'),
        'AW'=>array('name'=>'ARUBA','code'=>'297'),
        'AZ'=>array('name'=>'AZERBAIJAN','code'=>'994'),
        'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
        'BB'=>array('name'=>'BARBADOS','code'=>'1246'),
        'BD'=>array('name'=>'BANGLADESH','code'=>'880'),
        'BE'=>array('name'=>'BELGIUM','code'=>'32'),
        'BF'=>array('name'=>'BURKINA FASO','code'=>'226'),
        'BG'=>array('name'=>'BULGARIA','code'=>'359'),
        'BH'=>array('name'=>'BAHRAIN','code'=>'973'),
        'BI'=>array('name'=>'BURUNDI','code'=>'257'),
        'BJ'=>array('name'=>'BENIN','code'=>'229'),
        'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'590'),
        'BM'=>array('name'=>'BERMUDA','code'=>'1441'),
        'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'673'),
        'BO'=>array('name'=>'BOLIVIA','code'=>'591'),
        'BR'=>array('name'=>'BRAZIL','code'=>'55'),
        'BS'=>array('name'=>'BAHAMAS','code'=>'1242'),
        'BT'=>array('name'=>'BHUTAN','code'=>'975'),
        'BW'=>array('name'=>'BOTSWANA','code'=>'267'),
        'BY'=>array('name'=>'BELARUS','code'=>'375'),
        'BZ'=>array('name'=>'BELIZE','code'=>'501'),
        'CA'=>array('name'=>'CANADA','code'=>'1'),
        'CC'=>array('name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
        'CD'=>array('name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
        'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
        'CG'=>array('name'=>'CONGO','code'=>'242'),
        'CH'=>array('name'=>'SWITZERLAND','code'=>'41'),
        'CI'=>array('name'=>'COTE D IVOIRE','code'=>'225'),
        'CK'=>array('name'=>'COOK ISLANDS','code'=>'682'),
        'CL'=>array('name'=>'CHILE','code'=>'56'),
        'CM'=>array('name'=>'CAMEROON','code'=>'237'),
        'CN'=>array('name'=>'CHINA','code'=>'86'),
        'CO'=>array('name'=>'COLOMBIA','code'=>'57'),
        'CR'=>array('name'=>'COSTA RICA','code'=>'506'),
        'CU'=>array('name'=>'CUBA','code'=>'53'),
        'CV'=>array('name'=>'CAPE VERDE','code'=>'238'),
        'CX'=>array('name'=>'CHRISTMAS ISLAND','code'=>'61'),
        'CY'=>array('name'=>'CYPRUS','code'=>'357'),
        'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'420'),
        'DE'=>array('name'=>'GERMANY','code'=>'49'),
        'DJ'=>array('name'=>'DJIBOUTI','code'=>'253'),
        'DK'=>array('name'=>'DENMARK','code'=>'45'),
        'DM'=>array('name'=>'DOMINICA','code'=>'1767'),
        'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
        'DZ'=>array('name'=>'ALGERIA','code'=>'213'),
        'EC'=>array('name'=>'ECUADOR','code'=>'593'),
        'EE'=>array('name'=>'ESTONIA','code'=>'372'),
        'EG'=>array('name'=>'EGYPT','code'=>'20'),
        'ER'=>array('name'=>'ERITREA','code'=>'291'),
        'ES'=>array('name'=>'SPAIN','code'=>'34'),
        'ET'=>array('name'=>'ETHIOPIA','code'=>'251'),
        'FI'=>array('name'=>'FINLAND','code'=>'358'),
        'FJ'=>array('name'=>'FIJI','code'=>'679'),
        'FK'=>array('name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
        'FM'=>array('name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
        'FO'=>array('name'=>'FAROE ISLANDS','code'=>'298'),
        'FR'=>array('name'=>'FRANCE','code'=>'33'),
        'GA'=>array('name'=>'GABON','code'=>'241'),
        'GB'=>array('name'=>'UNITED KINGDOM','code'=>'44'),
        'GD'=>array('name'=>'GRENADA','code'=>'1473'),
        'GE'=>array('name'=>'GEORGIA','code'=>'995'),
        'GH'=>array('name'=>'GHANA','code'=>'233'),
        'GI'=>array('name'=>'GIBRALTAR','code'=>'350'),
        'GL'=>array('name'=>'GREENLAND','code'=>'299'),
        'GM'=>array('name'=>'GAMBIA','code'=>'220'),
        'GN'=>array('name'=>'GUINEA','code'=>'224'),
        'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'240'),
        'GR'=>array('name'=>'GREECE','code'=>'30'),
        'GT'=>array('name'=>'GUATEMALA','code'=>'502'),
        'GU'=>array('name'=>'GUAM','code'=>'1671'),
        'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'245'),
        'GY'=>array('name'=>'GUYANA','code'=>'592'),
        'HK'=>array('name'=>'HONG KONG','code'=>'852'),
        'HN'=>array('name'=>'HONDURAS','code'=>'504'),
        'HR'=>array('name'=>'CROATIA','code'=>'385'),
        'HT'=>array('name'=>'HAITI','code'=>'509'),
        'HU'=>array('name'=>'HUNGARY','code'=>'36'),
        'ID'=>array('name'=>'INDONESIA','code'=>'62'),
        'IE'=>array('name'=>'IRELAND','code'=>'353'),
        'IL'=>array('name'=>'ISRAEL','code'=>'972'),
        'IM'=>array('name'=>'ISLE OF MAN','code'=>'44'),
        'IN'=>array('name'=>'INDIA','code'=>'91'),
        'IQ'=>array('name'=>'IRAQ','code'=>'964'),
        'IR'=>array('name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
        'IS'=>array('name'=>'ICELAND','code'=>'354'),
        'IT'=>array('name'=>'ITALY','code'=>'39'),
        'JM'=>array('name'=>'JAMAICA','code'=>'1876'),
        'JO'=>array('name'=>'JORDAN','code'=>'962'),
        'JP'=>array('name'=>'JAPAN','code'=>'81'),
        'KE'=>array('name'=>'KENYA','code'=>'254'),
        'KG'=>array('name'=>'KYRGYZSTAN','code'=>'996'),
        'KH'=>array('name'=>'CAMBODIA','code'=>'855'),
        'KI'=>array('name'=>'KIRIBATI','code'=>'686'),
        'KM'=>array('name'=>'COMOROS','code'=>'269'),
        'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
        'KP'=>array('name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
        'KR'=>array('name'=>'KOREA REPUBLIC OF','code'=>'82'),
        'KW'=>array('name'=>'KUWAIT','code'=>'965'),
        'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'1345'),
        'KZ'=>array('name'=>'KAZAKSTAN','code'=>'7'),
        'LA'=>array('name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
        'LB'=>array('name'=>'LEBANON','code'=>'961'),
        'LC'=>array('name'=>'SAINT LUCIA','code'=>'1758'),
        'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'423'),
        'LK'=>array('name'=>'SRI LANKA','code'=>'94'),
        'LR'=>array('name'=>'LIBERIA','code'=>'231'),
        'LS'=>array('name'=>'LESOTHO','code'=>'266'),
        'LT'=>array('name'=>'LITHUANIA','code'=>'370'),
        'LU'=>array('name'=>'LUXEMBOURG','code'=>'352'),
        'LV'=>array('name'=>'LATVIA','code'=>'371'),
        'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
        'MA'=>array('name'=>'MOROCCO','code'=>'212'),
        'MC'=>array('name'=>'MONACO','code'=>'377'),
        'MD'=>array('name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
        'ME'=>array('name'=>'MONTENEGRO','code'=>'382'),
        'MF'=>array('name'=>'SAINT MARTIN','code'=>'1599'),
        'MG'=>array('name'=>'MADAGASCAR','code'=>'261'),
        'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'692'),
        'MK'=>array('name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
        'ML'=>array('name'=>'MALI','code'=>'223'),
        'MM'=>array('name'=>'MYANMAR','code'=>'95'),
        'MN'=>array('name'=>'MONGOLIA','code'=>'976'),
        'MO'=>array('name'=>'MACAU','code'=>'853'),
        'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
        'MR'=>array('name'=>'MAURITANIA','code'=>'222'),
        'MS'=>array('name'=>'MONTSERRAT','code'=>'1664'),
        'MT'=>array('name'=>'MALTA','code'=>'356'),
        'MU'=>array('name'=>'MAURITIUS','code'=>'230'),
        'MV'=>array('name'=>'MALDIVES','code'=>'960'),
        'MW'=>array('name'=>'MALAWI','code'=>'265'),
        'MX'=>array('name'=>'MEXICO','code'=>'52'),
        'MY'=>array('name'=>'MALAYSIA','code'=>'60'),
        'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'258'),
        'NA'=>array('name'=>'NAMIBIA','code'=>'264'),
        'NC'=>array('name'=>'NEW CALEDONIA','code'=>'687'),
        'NE'=>array('name'=>'NIGER','code'=>'227'),
        'NG'=>array('name'=>'NIGERIA','code'=>'234'),
        'NI'=>array('name'=>'NICARAGUA','code'=>'505'),
        'NL'=>array('name'=>'NETHERLANDS','code'=>'31'),
        'NO'=>array('name'=>'NORWAY','code'=>'47'),
        'NP'=>array('name'=>'NEPAL','code'=>'977'),
        'NR'=>array('name'=>'NAURU','code'=>'674'),
        'NU'=>array('name'=>'NIUE','code'=>'683'),
        'NZ'=>array('name'=>'NEW ZEALAND','code'=>'64'),
        'OM'=>array('name'=>'OMAN','code'=>'968'),
        'PA'=>array('name'=>'PANAMA','code'=>'507'),
        'PE'=>array('name'=>'PERU','code'=>'51'),
        'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'689'),
        'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'675'),
        'PH'=>array('name'=>'PHILIPPINES','code'=>'63'),
        'PK'=>array('name'=>'PAKISTAN','code'=>'92'),
        'PL'=>array('name'=>'POLAND','code'=>'48'),
        'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
        'PN'=>array('name'=>'PITCAIRN','code'=>'870'),
        'PT'=>array('name'=>'PORTUGAL','code'=>'351'),
        'PW'=>array('name'=>'PALAU','code'=>'680'),
        'PY'=>array('name'=>'PARAGUAY','code'=>'595'),
        'QA'=>array('name'=>'QATAR','code'=>'974'),
        'RO'=>array('name'=>'ROMANIA','code'=>'40'),
        'RS'=>array('name'=>'SERBIA','code'=>'381'),
        'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'7'),
        'RW'=>array('name'=>'RWANDA','code'=>'250'),
        'SA'=>array('name'=>'SAUDI ARABIA','code'=>'966'),
        'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'677'),
        'SC'=>array('name'=>'SEYCHELLES','code'=>'248'),
        'SD'=>array('name'=>'SUDAN','code'=>'249'),
        'SE'=>array('name'=>'SWEDEN','code'=>'46'),
        'SG'=>array('name'=>'SINGAPORE','code'=>'65'),
        'SH'=>array('name'=>'SAINT HELENA','code'=>'290'),
        'SI'=>array('name'=>'SLOVENIA','code'=>'386'),
        'SK'=>array('name'=>'SLOVAKIA','code'=>'421'),
        'SL'=>array('name'=>'SIERRA LEONE','code'=>'232'),
        'SM'=>array('name'=>'SAN MARINO','code'=>'378'),
        'SN'=>array('name'=>'SENEGAL','code'=>'221'),
        'SO'=>array('name'=>'SOMALIA','code'=>'252'),
        'SR'=>array('name'=>'SURINAME','code'=>'597'),
        'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
        'SV'=>array('name'=>'EL SALVADOR','code'=>'503'),
        'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
        'SZ'=>array('name'=>'SWAZILAND','code'=>'268'),
        'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
        'TD'=>array('name'=>'CHAD','code'=>'235'),
        'TG'=>array('name'=>'TOGO','code'=>'228'),
        'TH'=>array('name'=>'THAILAND','code'=>'66'),
        'TJ'=>array('name'=>'TAJIKISTAN','code'=>'992'),
        'TK'=>array('name'=>'TOKELAU','code'=>'690'),
        'TL'=>array('name'=>'TIMOR-LESTE','code'=>'670'),
        'TM'=>array('name'=>'TURKMENISTAN','code'=>'993'),
        'TN'=>array('name'=>'TUNISIA','code'=>'216'),
        'TO'=>array('name'=>'TONGA','code'=>'676'),
        'TR'=>array('name'=>'TURKEY','code'=>'90'),
        'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
        'TV'=>array('name'=>'TUVALU','code'=>'688'),
        'TW'=>array('name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
        'TZ'=>array('name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
        'UA'=>array('name'=>'UKRAINE','code'=>'380'),
        'UG'=>array('name'=>'UGANDA','code'=>'256'),
        'UY'=>array('name'=>'URUGUAY','code'=>'598'),
        'UZ'=>array('name'=>'UZBEKISTAN','code'=>'998'),
        'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
        'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
        'VE'=>array('name'=>'VENEZUELA','code'=>'58'),
        'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
        'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
        'VN'=>array('name'=>'VIET NAM','code'=>'84'),
        'VU'=>array('name'=>'VANUATU','code'=>'678'),
        'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'681'),
        'WS'=>array('name'=>'SAMOA','code'=>'685'),
        'XK'=>array('name'=>'KOSOVO','code'=>'381'),
        'YE'=>array('name'=>'YEMEN','code'=>'967'),
        'YT'=>array('name'=>'MAYOTTE','code'=>'262'),
        'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'27'),
        'ZM'=>array('name'=>'ZAMBIA','code'=>'260'),
        'ZW'=>array('name'=>'ZIMBABWE','code'=>'263')
    );

    const TIMEZONES = array(
          0 => "Africa/Abidjan",
          1 => "Africa/Accra",
          2 => "Africa/Addis_Ababa",
          3 => "Africa/Algiers",
          4 => "Africa/Asmara",
          5 => "Africa/Bamako",
          6 => "Africa/Bangui",
          7 => "Africa/Banjul",
          8 => "Africa/Bissau",
          9 => "Africa/Blantyre",
          10 => "Africa/Brazzaville",
          11 => "Africa/Bujumbura",
          12 => "Africa/Cairo",
          13 => "Africa/Casablanca",
          14 => "Africa/Ceuta",
          15 => "Africa/Conakry",
          16 => "Africa/Dakar",
          17 => "Africa/Dar_es_Salaam",
          18 => "Africa/Djibouti",
          19 => "Africa/Douala",
          20 => "Africa/El_Aaiun",
          21 => "Africa/Freetown",
          22 => "Africa/Gaborone",
          23 => "Africa/Harare",
          24 => "Africa/Johannesburg",
          25 => "Africa/Juba",
          26 => "Africa/Kampala",
          27 => "Africa/Khartoum",
          28 => "Africa/Kigali",
          29 => "Africa/Kinshasa",
          30 => "Africa/Lagos",
          31 => "Africa/Libreville",
          32 => "Africa/Lome",
          33 => "Africa/Luanda",
          34 => "Africa/Lubumbashi",
          35 => "Africa/Lusaka",
          36 => "Africa/Malabo",
          37 => "Africa/Maputo",
          38 => "Africa/Maseru",
          39 => "Africa/Mbabane",
          40 => "Africa/Mogadishu",
          41 => "Africa/Monrovia",
          42 => "Africa/Nairobi",
          43 => "Africa/Ndjamena",
          44 => "Africa/Niamey",
          45 => "Africa/Nouakchott",
          46 => "Africa/Ouagadougou",
          47 => "Africa/Porto-Novo",
          48 => "Africa/Sao_Tome",
          49 => "Africa/Tripoli",
          50 => "Africa/Tunis",
          51 => "Africa/Windhoek",
          52 => "America/Adak",
          53 => "America/Anchorage",
          54 => "America/Anguilla",
          55 => "America/Antigua",
          56 => "America/Araguaina",
          57 => "America/Argentina/Buenos_Aires",
          58 => "America/Argentina/Catamarca",
          59 => "America/Argentina/Cordoba",
          60 => "America/Argentina/Jujuy",
          61 => "America/Argentina/La_Rioja",
          62 => "America/Argentina/Mendoza",
          63 => "America/Argentina/Rio_Gallegos",
          64 => "America/Argentina/Salta",
          65 => "America/Argentina/San_Juan",
          66 => "America/Argentina/San_Luis",
          67 => "America/Argentina/Tucuman",
          68 => "America/Argentina/Ushuaia",
          69 => "America/Aruba",
          70 => "America/Asuncion",
          71 => "America/Atikokan",
          72 => "America/Bahia",
          73 => "America/Bahia_Banderas",
          74 => "America/Barbados",
          75 => "America/Belem",
          76 => "America/Belize",
          77 => "America/Blanc-Sablon",
          78 => "America/Boa_Vista",
          79 => "America/Bogota",
          80 => "America/Boise",
          81 => "America/Cambridge_Bay",
          82 => "America/Campo_Grande",
          83 => "America/Cancun",
          84 => "America/Caracas",
          85 => "America/Cayenne",
          86 => "America/Cayman",
          87 => "America/Chicago",
          88 => "America/Chihuahua",
          89 => "America/Costa_Rica",
          90 => "America/Creston",
          91 => "America/Cuiaba",
          92 => "America/Curacao",
          93 => "America/Danmarkshavn",
          94 => "America/Dawson",
          95 => "America/Dawson_Creek",
          96 => "America/Denver",
          97 => "America/Detroit",
          98 => "America/Dominica",
          99 => "America/Edmonton",
          100 => "America/Eirunepe",
          101 => "America/El_Salvador",
          102 => "America/Fort_Nelson",
          103 => "America/Fortaleza",
          104 => "America/Glace_Bay",
          105 => "America/Godthab",
          106 => "America/Goose_Bay",
          107 => "America/Grand_Turk",
          108 => "America/Grenada",
          109 => "America/Guadeloupe",
          110 => "America/Guatemala",
          111 => "America/Guayaquil",
          112 => "America/Guyana",
          113 => "America/Halifax",
          114 => "America/Havana",
          115 => "America/Hermosillo",
          116 => "America/Indiana/Indianapolis",
          117 => "America/Indiana/Knox",
          118 => "America/Indiana/Marengo",
          119 => "America/Indiana/Petersburg",
          120 => "America/Indiana/Tell_City",
          121 => "America/Indiana/Vevay",
          122 => "America/Indiana/Vincennes",
          123 => "America/Indiana/Winamac",
          124 => "America/Inuvik",
          125 => "America/Iqaluit",
          126 => "America/Jamaica",
          127 => "America/Juneau",
          128 => "America/Kentucky/Louisville",
          129 => "America/Kentucky/Monticello",
          130 => "America/Kralendijk",
          131 => "America/La_Paz",
          132 => "America/Lima",
          133 => "America/Los_Angeles",
          134 => "America/Lower_Princes",
          135 => "America/Maceio",
          136 => "America/Managua",
          137 => "America/Manaus",
          138 => "America/Marigot",
          139 => "America/Martinique",
          140 => "America/Matamoros",
          141 => "America/Mazatlan",
          142 => "America/Menominee",
          143 => "America/Merida",
          144 => "America/Metlakatla",
          145 => "America/Mexico_City",
          146 => "America/Miquelon",
          147 => "America/Moncton",
          148 => "America/Monterrey",
          149 => "America/Montevideo",
          150 => "America/Montserrat",
          151 => "America/Nassau",
          152 => "America/New_York",
          153 => "America/Nipigon",
          154 => "America/Nome",
          155 => "America/Noronha",
          156 => "America/North_Dakota/Beulah",
          157 => "America/North_Dakota/Center",
          158 => "America/North_Dakota/New_Salem",
          159 => "America/Ojinaga",
          160 => "America/Panama",
          161 => "America/Pangnirtung",
          162 => "America/Paramaribo",
          163 => "America/Phoenix",
          164 => "America/Port-au-Prince",
          165 => "America/Port_of_Spain",
          166 => "America/Porto_Velho",
          167 => "America/Puerto_Rico",
          168 => "America/Punta_Arenas",
          169 => "America/Rainy_River",
          170 => "America/Rankin_Inlet",
          171 => "America/Recife",
          172 => "America/Regina",
          173 => "America/Resolute",
          174 => "America/Rio_Branco",
          175 => "America/Santarem",
          176 => "America/Santiago",
          177 => "America/Santo_Domingo",
          178 => "America/Sao_Paulo",
          179 => "America/Scoresbysund",
          180 => "America/Sitka",
          181 => "America/St_Barthelemy",
          182 => "America/St_Johns",
          183 => "America/St_Kitts",
          184 => "America/St_Lucia",
          185 => "America/St_Thomas",
          186 => "America/St_Vincent",
          187 => "America/Swift_Current",
          188 => "America/Tegucigalpa",
          189 => "America/Thule",
          190 => "America/Thunder_Bay",
          191 => "America/Tijuana",
          192 => "America/Toronto",
          193 => "America/Tortola",
          194 => "America/Vancouver",
          195 => "America/Whitehorse",
          196 => "America/Winnipeg",
          197 => "America/Yakutat",
          198 => "America/Yellowknife",
          199 => "Antarctica/Casey",
          200 => "Antarctica/Davis",
          201 => "Antarctica/DumontDUrville",
          202 => "Antarctica/Macquarie",
          203 => "Antarctica/Mawson",
          204 => "Antarctica/McMurdo",
          205 => "Antarctica/Palmer",
          206 => "Antarctica/Rothera",
          207 => "Antarctica/Syowa",
          208 => "Antarctica/Troll",
          209 => "Antarctica/Vostok",
          210 => "Arctic/Longyearbyen",
          211 => "Asia/Aden",
          212 => "Asia/Almaty",
          213 => "Asia/Amman",
          214 => "Asia/Anadyr",
          215 => "Asia/Aqtau",
          216 => "Asia/Aqtobe",
          217 => "Asia/Ashgabat",
          218 => "Asia/Atyrau",
          219 => "Asia/Baghdad",
          220 => "Asia/Bahrain",
          221 => "Asia/Baku",
          222 => "Asia/Bangkok",
          223 => "Asia/Barnaul",
          224 => "Asia/Beirut",
          225 => "Asia/Bishkek",
          226 => "Asia/Brunei",
          227 => "Asia/Chita",
          228 => "Asia/Choibalsan",
          229 => "Asia/Colombo",
          230 => "Asia/Damascus",
          231 => "Asia/Dhaka",
          232 => "Asia/Dili",
          233 => "Asia/Dubai",
          234 => "Asia/Dushanbe",
          235 => "Asia/Famagusta",
          236 => "Asia/Gaza",
          237 => "Asia/Hebron",
          238 => "Asia/Ho_Chi_Minh",
          239 => "Asia/Hong_Kong",
          240 => "Asia/Hovd",
          241 => "Asia/Irkutsk",
          242 => "Asia/Jakarta",
          243 => "Asia/Jayapura",
          244 => "Asia/Jerusalem",
          245 => "Asia/Kabul",
          246 => "Asia/Kamchatka",
          247 => "Asia/Karachi",
          248 => "Asia/Kathmandu",
          249 => "Asia/Khandyga",
          250 => "Asia/Kolkata",
          251 => "Asia/Krasnoyarsk",
          252 => "Asia/Kuala_Lumpur",
          253 => "Asia/Kuching",
          254 => "Asia/Kuwait",
          255 => "Asia/Macau",
          256 => "Asia/Magadan",
          257 => "Asia/Makassar",
          258 => "Asia/Manila",
          259 => "Asia/Muscat",
          260 => "Asia/Nicosia",
          261 => "Asia/Novokuznetsk",
          262 => "Asia/Novosibirsk",
          263 => "Asia/Omsk",
          264 => "Asia/Oral",
          265 => "Asia/Phnom_Penh",
          266 => "Asia/Pontianak",
          267 => "Asia/Pyongyang",
          268 => "Asia/Qatar",
          269 => "Asia/Qyzylorda",
          270 => "Asia/Riyadh",
          271 => "Asia/Sakhalin",
          272 => "Asia/Samarkand",
          273 => "Asia/Seoul",
          274 => "Asia/Shanghai",
          275 => "Asia/Singapore",
          276 => "Asia/Srednekolymsk",
          277 => "Asia/Taipei",
          278 => "Asia/Tashkent",
          279 => "Asia/Tbilisi",
          280 => "Asia/Tehran",
          281 => "Asia/Thimphu",
          282 => "Asia/Tokyo",
          283 => "Asia/Tomsk",
          284 => "Asia/Ulaanbaatar",
          285 => "Asia/Urumqi",
          286 => "Asia/Ust-Nera",
          287 => "Asia/Vientiane",
          288 => "Asia/Vladivostok",
          289 => "Asia/Yakutsk",
          290 => "Asia/Yangon",
          291 => "Asia/Yekaterinburg",
          292 => "Asia/Yerevan",
          293 => "Atlantic/Azores",
          294 => "Atlantic/Bermuda",
          295 => "Atlantic/Canary",
          296 => "Atlantic/Cape_Verde",
          297 => "Atlantic/Faroe",
          298 => "Atlantic/Madeira",
          299 => "Atlantic/Reykjavik",
          300 => "Atlantic/South_Georgia",
          301 => "Atlantic/St_Helena",
          302 => "Atlantic/Stanley",
          303 => "Australia/Adelaide",
          304 => "Australia/Brisbane",
          305 => "Australia/Broken_Hill",
          306 => "Australia/Currie",
          307 => "Australia/Darwin",
          308 => "Australia/Eucla",
          309 => "Australia/Hobart",
          310 => "Australia/Lindeman",
          311 => "Australia/Lord_Howe",
          312 => "Australia/Melbourne",
          313 => "Australia/Perth",
          314 => "Australia/Sydney",
          315 => "Europe/Amsterdam",
          316 => "Europe/Andorra",
          317 => "Europe/Astrakhan",
          318 => "Europe/Athens",
          319 => "Europe/Belgrade",
          320 => "Europe/Berlin",
          321 => "Europe/Bratislava",
          322 => "Europe/Brussels",
          323 => "Europe/Bucharest",
          324 => "Europe/Budapest",
          325 => "Europe/Busingen",
          326 => "Europe/Chisinau",
          327 => "Europe/Copenhagen",
          328 => "Europe/Dublin",
          329 => "Europe/Gibraltar",
          330 => "Europe/Guernsey",
          331 => "Europe/Helsinki",
          332 => "Europe/Isle_of_Man",
          333 => "Europe/Istanbul",
          334 => "Europe/Jersey",
          335 => "Europe/Kaliningrad",
          336 => "Europe/Kiev",
          337 => "Europe/Kirov",
          338 => "Europe/Lisbon",
          339 => "Europe/Ljubljana",
          340 => "Europe/London",
          341 => "Europe/Luxembourg",
          342 => "Europe/Madrid",
          343 => "Europe/Malta",
          344 => "Europe/Mariehamn",
          345 => "Europe/Minsk",
          346 => "Europe/Monaco",
          347 => "Europe/Moscow",
          348 => "Europe/Oslo",
          349 => "Europe/Paris",
          350 => "Europe/Podgorica",
          351 => "Europe/Prague",
          352 => "Europe/Riga",
          353 => "Europe/Rome",
          354 => "Europe/Samara",
          355 => "Europe/San_Marino",
          356 => "Europe/Sarajevo",
          357 => "Europe/Saratov",
          358 => "Europe/Simferopol",
          359 => "Europe/Skopje",
          360 => "Europe/Sofia",
          361 => "Europe/Stockholm",
          362 => "Europe/Tallinn",
          363 => "Europe/Tirane",
          364 => "Europe/Ulyanovsk",
          365 => "Europe/Uzhgorod",
          366 => "Europe/Vaduz",
          367 => "Europe/Vatican",
          368 => "Europe/Vienna",
          369 => "Europe/Vilnius",
          370 => "Europe/Volgograd",
          371 => "Europe/Warsaw",
          372 => "Europe/Zagreb",
          373 => "Europe/Zaporozhye",
          374 => "Europe/Zurich",
          375 => "Indian/Antananarivo",
          376 => "Indian/Chagos",
          377 => "Indian/Christmas",
          378 => "Indian/Cocos",
          379 => "Indian/Comoro",
          380 => "Indian/Kerguelen",
          381 => "Indian/Mahe",
          382 => "Indian/Maldives",
          383 => "Indian/Mauritius",
          384 => "Indian/Mayotte",
          385 => "Indian/Reunion",
          386 => "Pacific/Apia",
          387 => "Pacific/Auckland",
          388 => "Pacific/Bougainville",
          389 => "Pacific/Chatham",
          390 => "Pacific/Chuuk",
          391 => "Pacific/Easter",
          392 => "Pacific/Efate",
          393 => "Pacific/Enderbury",
          394 => "Pacific/Fakaofo",
          395 => "Pacific/Fiji",
          396 => "Pacific/Funafuti",
          397 => "Pacific/Galapagos",
          398 => "Pacific/Gambier",
          399 => "Pacific/Guadalcanal",
          400 => "Pacific/Guam",
          401 => "Pacific/Honolulu",
          402 => "Pacific/Kiritimati",
          403 => "Pacific/Kosrae",
          404 => "Pacific/Kwajalein",
          405 => "Pacific/Majuro",
          406 => "Pacific/Marquesas",
          407 => "Pacific/Midway",
          408 => "Pacific/Nauru",
          409 => "Pacific/Niue",
          410 => "Pacific/Norfolk",
          411 => "Pacific/Noumea",
          412 => "Pacific/Pago_Pago",
          413 => "Pacific/Palau",
          414 => "Pacific/Pitcairn",
          415 => "Pacific/Pohnpei",
          416 => "Pacific/Port_Moresby",
          417 => "Pacific/Rarotonga",
          418 => "Pacific/Saipan",
          419 => "Pacific/Tahiti",
          420 => "Pacific/Tarawa",
          421 => "Pacific/Tongatapu",
          422 => "Pacific/Wake",
          423 => "Pacific/Wallis",
          424 => "UTC"
    );



   const LANGUAGES = array(
        'en' => 'English' ,
        'aa' => 'Afar' ,
        'ab' => 'Abkhazian' ,
        'af' => 'Afrikaans' ,
        'am' => 'Amharic' ,
        'ar' => 'Arabic' ,
        'as' => 'Assamese' ,
        'ay' => 'Aymara' ,
        'az' => 'Azerbaijani' ,
        'ba' => 'Bashkir' ,
        'be' => 'Byelorussian' ,
        'bg' => 'Bulgarian' ,
        'bh' => 'Bihari' ,
        'bi' => 'Bislama' ,
        'bn' => 'Bengali/Bangla' ,
        'bo' => 'Tibetan' ,
        'br' => 'Breton' ,
        'ca' => 'Catalan' ,
        'co' => 'Corsican' ,
        'cs' => 'Czech' ,
        'cy' => 'Welsh' ,
        'da' => 'Danish' ,
        'de' => 'German' ,
        'dz' => 'Bhutani' ,
        'el' => 'Greek' ,
        'eo' => 'Esperanto' ,
        'es' => 'Spanish' ,
        'et' => 'Estonian' ,
        'eu' => 'Basque' ,
        'fa' => 'Persian' ,
        'fi' => 'Finnish' ,
        'fj' => 'Fiji' ,
        'fo' => 'Faeroese' ,
        'fr' => 'French' ,
        'fy' => 'Frisian' ,
        'ga' => 'Irish' ,
        'gd' => 'Scots/Gaelic' ,
        'gl' => 'Galician' ,
        'gn' => 'Guarani' ,
        'gu' => 'Gujarati' ,
        'ha' => 'Hausa' ,
        'hi' => 'Hindi' ,
        'hr' => 'Croatian' ,
        'hu' => 'Hungarian' ,
        'hy' => 'Armenian' ,
        'ia' => 'Interlingua' ,
        'ie' => 'Interlingue' ,
        'ik' => 'Inupiak' ,
        'in' => 'Indonesian' ,
        'is' => 'Icelandic' ,
        'it' => 'Italian' ,
        'iw' => 'Hebrew' ,
        'ja' => 'Japanese' ,
        'ji' => 'Yiddish' ,
        'jw' => 'Javanese' ,
        'ka' => 'Georgian' ,
        'kk' => 'Kazakh' ,
        'kl' => 'Greenlandic' ,
        'km' => 'Cambodian' ,
        'kn' => 'Kannada' ,
        'ko' => 'Korean' ,
        'ks' => 'Kashmiri' ,
        'ku' => 'Kurdish' ,
        'ky' => 'Kirghiz' ,
        'la' => 'Latin' ,
        'ln' => 'Lingala' ,
        'lo' => 'Laothian' ,
        'lt' => 'Lithuanian' ,
        'lv' => 'Latvian/Lettish' ,
        'mg' => 'Malagasy' ,
        'mi' => 'Maori' ,
        'mk' => 'Macedonian' ,
        'ml' => 'Malayalam' ,
        'mn' => 'Mongolian' ,
        'mo' => 'Moldavian' ,
        'mr' => 'Marathi' ,
        'ms' => 'Malay' ,
        'mt' => 'Maltese' ,
        'my' => 'Burmese' ,
        'na' => 'Nauru' ,
        'ne' => 'Nepali' ,
        'nl' => 'Dutch' ,
        'no' => 'Norwegian' ,
        'oc' => 'Occitan' ,
        'om' => '(Afan)/Oromoor/Oriya' ,
        'pa' => 'Punjabi' ,
        'pl' => 'Polish' ,
        'ps' => 'Pashto/Pushto' ,
        'pt' => 'Portuguese' ,
        'qu' => 'Quechua' ,
        'rm' => 'Rhaeto-Romance' ,
        'rn' => 'Kirundi' ,
        'ro' => 'Romanian' ,
        'ru' => 'Russian' ,
        'rw' => 'Kinyarwanda' ,
        'sa' => 'Sanskrit' ,
        'sd' => 'Sindhi' ,
        'sg' => 'Sangro' ,
        'sh' => 'Serbo-Croatian' ,
        'si' => 'Singhalese' ,
        'sk' => 'Slovak' ,
        'sl' => 'Slovenian' ,
        'sm' => 'Samoan' ,
        'sn' => 'Shona' ,
        'so' => 'Somali' ,
        'sq' => 'Albanian' ,
        'sr' => 'Serbian' ,
        'ss' => 'Siswati' ,
        'st' => 'Sesotho' ,
        'su' => 'Sundanese' ,
        'sv' => 'Swedish' ,
        'sw' => 'Swahili' ,
        'ta' => 'Tamil' ,
        'te' => 'Tegulu' ,
        'tg' => 'Tajik' ,
        'th' => 'Thai' ,
        'ti' => 'Tigrinya' ,
        'tk' => 'Turkmen' ,
        'tl' => 'Tagalog' ,
        'tn' => 'Setswana' ,
        'to' => 'Tonga' ,
        'tr' => 'Turkish' ,
        'ts' => 'Tsonga' ,
        'tt' => 'Tatar' ,
        'tw' => 'Twi' ,
        'uk' => 'Ukrainian' ,
        'ur' => 'Urdu' ,
        'uz' => 'Uzbek' ,
        'vi' => 'Vietnamese' ,
        'vo' => 'Volapuk' ,
        'wo' => 'Wolof' ,
        'xh' => 'Xhosa' ,
        'yo' => 'Yoruba' ,
        'zh' => 'Chinese' ,
        'zu' => 'Zulu' ,
    );

   const ADDTLLANGUAGES = array(
        1 => 'Arabic',
        2 => 'Bengali',
        3 => 'Cantonese',
        4 => 'English',
        5 => 'French',
        6 => 'German',
        7 => 'Hindi',
        8 => 'Italian',
        9 => 'Japanese',
        10 => 'Mandarin',
        11 => 'Polish',
        12 => 'Portuguese',
        13 => 'Punjab',
        14 => 'Russian',
        15 => 'Spanish',
        16 => 'Tagalog',
        17 => 'Vietnamese',
        18 => 'Other'
   );


    const NATIONALITY = array(
        1 => 'White',
        2 => 'Asian',
        3 => 'Black/African American',
        4 => 'American Indian/ Alaska Native',
        5 => 'Native Hawaiian/ Other Pacific Islander',
        6 => 'Hispanic/Latino/ Spanish Origin',
        7 => 'Other'
    );

    const COUNTRIES = array("United States","Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao, People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");


    const DB_MAP_VALUES = array(

        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
        'phone' => 'Phone',
        'address' => 'Address Line 1',
        'address_two' => 'Address Line 2',
        'city' => 'City',
        'state' => 'State',
        'postal_code' => 'Postal Code',
        'country' => 'Country',
        'organization' => 'Previous Organization',
        'job_level' => 'Job Level',
        'dob' => 'Date of Birth'

    );

    const DB_MAP_KEYS = array(

        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
        'phone' => 'Phone',
        'address' => 'Address Line 1',
        'address_two' => 'Address Line 2',
        'city' => 'City',
        'state' => 'State',
        'postal_code' => 'Postal Code',
        'country' => 'Country',
        'organization' => 'Previous Organization',
        'job_level' => 'Job Level',
        'dob' => 'Date of Birth'

    );

    const ORDER_REVIEW_META = array(

        1 => 'address',
        2 => 'address_two',
        3 => 'phone',
        4 => 'native_language',
        6 => 'dob',
        9 => 'organization',
        10 => 'job_level',
    );

    const STATES = array(
        'AL'=>'ALABAMA',
        'AK'=>'ALASKA',
        'AS'=>'AMERICAN SAMOA',
        'AZ'=>'ARIZONA',
        'AR'=>'ARKANSAS',
        'CA'=>'CALIFORNIA',
        'CO'=>'COLORADO',
        'CT'=>'CONNECTICUT',
        'DE'=>'DELAWARE',
        'DC'=>'DISTRICT OF COLUMBIA',
        'FM'=>'FEDERATED STATES OF MICRONESIA',
        'FL'=>'FLORIDA',
        'GA'=>'GEORGIA',
        'GU'=>'GUAM GU',
        'HI'=>'HAWAII',
        'ID'=>'IDAHO',
        'IL'=>'ILLINOIS',
        'IN'=>'INDIANA',
        'IA'=>'IOWA',
        'KS'=>'KANSAS',
        'KY'=>'KENTUCKY',
        'LA'=>'LOUISIANA',
        'ME'=>'MAINE',
        'MH'=>'MARSHALL ISLANDS',
        'MD'=>'MARYLAND',
        'MA'=>'MASSACHUSETTS',
        'MI'=>'MICHIGAN',
        'MN'=>'MINNESOTA',
        'MS'=>'MISSISSIPPI',
        'MO'=>'MISSOURI',
        'MT'=>'MONTANA',
        'NE'=>'NEBRASKA',
        'NV'=>'NEVADA',
        'NH'=>'NEW HAMPSHIRE',
        'NJ'=>'NEW JERSEY',
        'NM'=>'NEW MEXICO',
        'NY'=>'NEW YORK',
        'NC'=>'NORTH CAROLINA',
        'ND'=>'NORTH DAKOTA',
        'MP'=>'NORTHERN MARIANA ISLANDS',
        'OH'=>'OHIO',
        'OK'=>'OKLAHOMA',
        'OR'=>'OREGON',
        'PW'=>'PALAU',
        'PA'=>'PENNSYLVANIA',
        'PR'=>'PUERTO RICO',
        'RI'=>'RHODE ISLAND',
        'SC'=>'SOUTH CAROLINA',
        'SD'=>'SOUTH DAKOTA',
        'TN'=>'TENNESSEE',
        'TX'=>'TEXAS',
        'UT'=>'UTAH',
        'VT'=>'VERMONT',
        'VI'=>'VIRGIN ISLANDS',
        'VA'=>'VIRGINIA',
        'WA'=>'WASHINGTON',
        'WV'=>'WEST VIRGINIA',
        'WI'=>'WISCONSIN',
        'WY'=>'WYOMING',
        'AE'=>'ARMED FORCES AFRICA \ CANADA \ EUROPE \ MIDDLE EAST',
        'AA'=>'ARMED FORCES AMERICA (EXCEPT CANADA)',
        'AP'=>'ARMED FORCES PACIFIC'
    );



    const NB_CATS = array(

        1 => 'Orientation',
        2 => 'High Performance',
        3 => 'Sleep Well',
        4 => 'Personal Philosophy',
        5 => 'Vision',
        6 => 'Character',
        7 => 'Mindfulness',
        8 => 'Eat & Hydrate Well',
        9 => 'Optimism',
        10 => 'Control',
        11 => 'Grit',
        12 => 'Calm',
        13 => 'Confidence',
        14 => 'Move Well',
        15 => 'Focus',
        16 => 'Trust',
        17 => 'Culture',
        18 => 'Think Well',
        19 => 'Wrap Up',
        20 => 'Personal'
    );

    const COURSE_WEEK_ORDER = array(
        0 => [
            'Orientation',
            'High Performance',
            'Sleep Well'
        ],
        1 => [
            'Personal Philosophy',
            'Vision',
            'Character'
        ],
        2 => [
            'Mindfulness',
            'Optimism'
        ],
        3 => [
            'Control',
            'Eat & Hydrate Well'
        ],
        4 => [
            'Grit',
            'Calm'
        ],
        5 => [
            'Confidence',
            'Move Well'
        ],
        6 => [
            'Focus',
            'Trust'
        ],
        7 => [
            'Culture',
            'Think Well'
        ],
        8 => [
            'Wrap Up'
        ]
    );

    const PURE_COURSE_ORDER = array(
        0 => 'Orientation',
        1 => 'High Performance',
        2 => 'Sleep Well',
        3 => 'Personal Philosophy',
        4 => 'Vision',
        5 => 'Character',
        6 => 'Mindfulness',
        7 => 'Optimism',
        8 => 'Control',
        9 => 'Eat & Hydrate Well',
        10 => 'Grit',
        11 => 'Calm',
        12 => 'Confidence',
        13 => 'Move Well',
        14 => 'Focus',
        15 => 'Trust',
        16 => 'Culture',
        17 => 'Think Well',
        18 => 'Wrap Up'
    );


    const CONGRATS = array(
        0 => "You're on your way!",
        1 => 'Fantastic!',
        2 => 'Amazing!',
        3 => 'Way to compete!',
        4 => 'You rock!',
        5 => 'Crushing it!',
        6 => "You've Got This!",
        7 => 'Cruising along!',
        8 => 'Great Job!',
        9 => 'Nice Going!',
        10 => 'You Did It!',
        11 => "You've Done It!",
        12 => 'Good Work!',
        13 => 'Outstanding!',
        14 => 'Way to go!',
        15 => 'Excellent!',
        16 => 'Impressive!',
        17 => 'Terrific!',
        18 => "Congratulations!"
    );

    public static function datediffInWeeks($date1, $date2)
    {
        $cohortStartDate = new DateTime($date1);
        $cohortStartDate = $cohortStartDate->sub(new DateInterval('P1D'));  // Minus one day to reach sunday
        $today = new DateTime($date2);
        return floor($cohortStartDate->diff($today)->days / 7) + 1;
    }


    /*
     *
     * Shortcode Output
    */
    public static function shortcode($c){
        $user = Auth::user();
        $content = $c; // Assign string to new var
        preg_match('/"([^"]+)"/', $c, $assignmentID); // find Course ID in original string
        if(array_key_exists(0, $assignmentID)){
            //$aID = substr($assignmentID[0], 1, 2); // Get id from "id" 
            $aID = $assignmentID[1];

            if(!is_numeric($aID)){
                return $content;
            }

            $entry = $user->assignments()->where('assignment_id', $aID)->first();
            if($entry){
                $content = preg_replace('#\[.*?\]#s', '<strong>'.$entry->pivot->entry.'</strong>', $content);
                return $content;
            }

        } else {
            return $content; // No Shortcode
        }
    }



    public static function convertDBValue($key, $value) {

        if (!$value || !$key) {
            return;
        };

        if (isset(self::DB_MAP_VALUES[$key])) {

            return ($value);

        }

        return $value;
    }



    public static function convertDBKey($key) {

        if (isset(self::DB_MAP_KEYS[$key])) {

            return (self::DB_MAP_KEYS[$key]);

        }

        return $key;
    }


}